version: '3'
services:
  app:
    container_name: app
    build: .
    ports: ["8080:8080"]
    environment:
      POSTGRES_HOST: pg://postgres:mdp@postgres:5432
      PORT: 8080
    depends_on:
      - db
    links:
      - db
    command: npm start

  db:
    container_name: postgres
    restart: always
    image: postgres:11.2-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: db